# Generated by Django 5.1.15 on 2026-03-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_legalcase_status_changed_at_legalcaseevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='specialty',
            field=models.CharField(help_text='Ex: droit familial, droit penal', max_length=100),
        ),
        migrations.AlterField(
            model_name='legalcase',
            name='is_anonymous',
            field=models.BooleanField(default=True, help_text="Garder l'identite confidentielle"),
        ),
        migrations.AlterField(
            model_name='legalcase',
            name='status',
            field=models.CharField(choices=[('submitted', 'Soumis'), ('in_review', "En cours d'examen"), ('assigned', 'Assigne a un avocat'), ('in_progress', 'En cours'), ('resolved', 'Resolu'), ('closed', 'Ferme')], default='submitted', max_length=20),
        ),
    ]
