# Generated by Django 5.2.12 on 2026-03-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discreetappsettings',
            name='pin_code',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
