# Generated by Django 5.1.15 on 2026-03-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_alter_discreetappsettings_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='public_tracking_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='tracking_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
