# Generated by Django 5.1.15 on 2026-03-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_sosalert_public_tracking_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='audio_evidence',
            field=models.FileField(blank=True, null=True, upload_to='sos/audio/'),
        ),
    ]
