# Generated by Django 5.1.15 on 2026-03-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_risk_assessment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='risk_score',
            field=models.FloatField(default=0.0, help_text='Calculated vulnerability score (0.0 - 1.0)'),
        ),
    ]
